# Generated by Django 5.0.3 on 2024-03-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
